title: Ulmus - Grav CMS
author:
  name: Charles Leverington
  email: 'charles.leverington@gmail.com'
metadata:
    description: Creating an open sharing environment for all

redirects:
    /internal: '/gravstrap-theme-versatile-internal-template[303]'
